version: '3.8'
services:
  nest-api:
    container_name: nest-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .prod.env
  postgres:
    image: postgres:15.1
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .prod.env
    volumes:
      - postgres:/var/lib/postgresq/data


volumes:
  postgres:
    name: nest-db
